//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficerShootingOfficer
    {
        public Nullable<int> INCIDENT_ID { get; set; }
        public string OFFICER_RACE { get; set; }
        public string OFFICER_GENDER { get; set; }
        public Nullable<double> OFFICER_EXPERIENCE_YEARS { get; set; }
        public string OFFICER_POLICY_VIOLATION { get; set; }
        public int ObjectID { get; set; }
        public Nullable<int> YR { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    }
}
