//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrafficStop
    {
        public int ObjectID { get; set; }
        public Nullable<System.DateTime> Stop_Date { get; set; }
        public string Reason_for_Stop { get; set; }
        public string Officer_Race { get; set; }
        public string Officer_Gender { get; set; }
        public Nullable<int> Officer_Years_of_Service { get; set; }
        public string Driver_Race { get; set; }
        public string Driver_Ethnicity { get; set; }
        public string Driver_Gender { get; set; }
        public Nullable<int> Driver_Age { get; set; }
        public string Was_a_Search_Conducted { get; set; }
        public string Result_of_Stop { get; set; }
        public string CMPD_Division { get; set; }
    }
}
