import NetworkService from './NetworkService';
//import DemographicSearch from './DemographicSearch';
//import TrafficSearch from './TrafficSearch';


//NetworkService.getDemographics()
//    .then(data => {
//        console.log("Get All Demographics");
//        console.log(data);
//    })
//    .catch(error => {
//        console.log(error);
//    });


//NetworkService.getDemographic(1)
//    .then(data => {
//        console.log("Get Demographic id = 1");
//        console.log(data);
//    })
//    .catch(error => {
//        console.log(error);
//    });

//NetworkService.getDemographicsOrdered('officerExperience', 'descending')
//    .then(data => {
//        console.log("Order Demographics by experience DESC");
//        console.log(data);
//    })
//    .catch(error => {
//        console.log(error);
//    });




//let demoSearch = new DemographicSearch(null, null, null, 26, 26, null, null);
//NetworkService.getDemographicsSearch(demoSearch)
//    .then(data => {
//        console.log("Search Demographics");
//        console.log(data);
//    })
//    .catch(error => {
//        console.log(error);
//    });

//NetworkService.getTrafficStops()
//    .then(data => {
//        console.log("Get All Stops");
//        console.log(data);
//    })
//    .catch(error => {
//        console.log(error);
//    });


//NetworkService.getTrafficStop(1)
//    .then(data => {
//        console.log("Get Stops id = 1");
//        console.log(data);
//    })
//    .catch(error => {
//        console.log(error);
//    });

//NetworkService.getTrafficStopsOrdered('date', 'descending')
//    .then(data => {
//        console.log("Get Stops ordered by date");
//        console.log(data);
//    })
//    .catch(error => {
//        console.log(error);
//    });

//const search = new TrafficSearch();
//search.officerGender = 'male';
//search.officerRace = 'white';

//NetworkService.getTrafficStopsSearch(search)
//    .then(data => {
//        console.log("search stops");
//        console.log(data);
//    })
//    .catch(error => {
//        console.log(error);
//    });