import NetworkService from './NetworkService';
import DemographicSearch from './DemographicSearch';
import TrafficSearch from './TrafficSearch';
import ShootingSearch from './ShootingSearch';


//NetworkService.getOfficerShootingsOrdered('date', 'descending')
//    .then(data => {
//        console.log("Get Stops ordered by date");
//        console.log(data);
//    })
//    .catch(error => {
//        console.log(error);
//    });

